name: Publish Docker image of Game7 testnet to public registry

on:
    push:
        branches:
            - "dev"

concurrency:
    group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
    cancel-in-progress: true

env:
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1
    RUNNING_ON_ENVIRONMENT_BRANCH: |
        ${{ github.ref_name == 'dev' }}

jobs:
    deploy:
        name: Build, Tag and Push to registry
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
              with:
                  ref: beta-dev

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to AWS Elastic Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.AWS_GAME7_PUBLIC_ECR }}/blockscout
                  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Add SHORT_SHA env property with commit short sha
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            - name: Debug
              env:
                  REF_TYPE: ${{ github.ref_type }}
                  REF_NAME: ${{ github.ref_name }}
              run: |
                  echo "ref_type: $REF_TYPE"
                  echo "ref_name: $REF_NAME"

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  cache-from: type=gha
                  tags: ${{ secrets.AWS_GAME7_PUBLIC_ECR }}/blockscout/blockscout-frontend:${{ env.SHORT_SHA }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
                      GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}
